[package]
name = "fancy-motd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = { path = "segments/quote" }
heading = { path = "segments/heading" }
disk = { path = "segments/disk" }
display = { path = "crates/display" }
user = { path = "segments/user" }
thiserror = "1.0.61"
anyhow = "1.0.86"

[workspace]
members = ["crates/*", "segments/*", "."]
default-members = ["crates/*", "segments/*", "."]
