[package]
name = "fancy-motd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = { path = "segments/quote" }
heading = { path = "segments/heading" }
display = { path = "crates/display" }

[workspace]
members = ["crates/*", "segments/*", "."]
default-members = ["crates/*", "segments/*", "."]
